### ISSUE TITLE
Aggregate and enforce caveats at each step

### ISSUE THREAD

**Issue by rekmarks** [MetaMask/json-rpc-capabilities-middleware#16]
Currently, only the `static` caveat is supported (see [here](https://github.com/MetaMask/json-rpc-capabilities-middleware/blob/master/index.js#L100-L108)), and caveats are not aggregated and enforced while traversing permission delegation trees (see [here](https://github.com/MetaMask/json-rpc-capabilities-middleware/blob/master/index.js#L137) and [here](https://github.com/MetaMask/json-rpc-capabilities-middleware/blob/master/index.js#L165)).

**Comment by danfinlay** [comment]
Done w/ middleware caveat refactor.
