### ISSUE TITLE
Minor TODOs

### ISSUE THREAD

**Issue by rekmarks** [MetaMask/json-rpc-capabilities-middleware#17]
- [ ] Split [`getPermission`](https://github.com/MetaMask/json-rpc-capabilities-middleware/blob/master/index.js#L130) into two methods: `getPermissionByMethod` and `getPermissionById`
    - [ ] Alternatively, make the existing method functionally equivalent by making the second argument an object, checking first for an `id` and then a `method` property.
- [x] Parameter/promise/request validation
    - [x] Remove duplicate permissions in [`addPermissionsFor`](https://github.com/MetaMask/json-rpc-capabilities-middleware/blob/master/index.js#L277)
    - [x] [`requestPermissionsMiddleware `](https://github.com/MetaMask/json-rpc-capabilities-middleware/blob/master/index.js#L338)
    - [x] [`grantPermissionsMiddleware`](https://github.com/MetaMask/json-rpc-capabilities-middleware/blob/master/index.js#L380)
    - [x] [`revokePermissionsMiddleware`](https://github.com/MetaMask/json-rpc-capabilities-middleware/blob/master/index.js#L425)
- [ ] `grantPermissionsMiddleware`: [Allow objects in `requestedPerms` to specify permission id](https://github.com/MetaMask/json-rpc-capabilities-middleware/blob/master/index.js#L381)
- [x] `requestUserApproval`: [Allow user to pass back an object describing the approved permissions](https://github.com/MetaMask/json-rpc-capabilities-middleware/blob/master/index.js#L356)

**Comment by danfinlay** [comment]
I wasn't sure about the permission ID items in here. I think the distinction may be that permissions requests have IDs (for the sake of responding to them), and permissions do also have an ID, but we don't have any need to look up by them for MVP.

So given that, I think we can close this for now, but I'll let you go over it to be sure.

**Comment by rekmarks** [comment]
Agree that ID lookup is, for MVP purposes, a nicety, and we can close this issue.
