### ISSUE TITLE
Standardize error codes

### ISSUE THREAD

**Issue by rekmarks** [MetaMask/json-rpc-capabilities-middleware#18]
RPC error codes need standardization. See e.g. [here](https://github.com/MetaMask/json-rpc-capabilities-middleware/blob/master/src/errors.ts#L26-L30).

Possible standards to adopt include EIP 1193, although we'd probably extend their error codes beyond their intended use. See https://eips.ethereum.org/EIPS/eip-1193, "Error object and codes".

We will attempt to add additional error codes and/or modify the error codes on EIP 1193. Working with one of the authors to accomplish this.

**Comment by danfinlay** [comment]
Deserves an EIP! Thanks for making an issue from the todo.

**Comment by rekmarks** [comment]
Updated EIP 1193: https://github.com/ethereum/EIPs/pull/2240

Incorporated in: https://www.npmjs.com/package/eth-json-rpc-errors
