### ISSUE TITLE
Cryptographic enhancement: Sign hash of description of granted permissions

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/json-rpc-capabilities-middleware#21]
If a permission's description is changed, those previous permissions should be invalidated, because it may imply that the previous permission was worded deceptively and consent was maybe given illegitimately.

Additionally, permissions objects are easy to forge for anyone who has disk access.

If we incorporated a signature of granted permissions into the grant flow (and maybe [app keys](https://github.com/ethereum/EIPs/pull/1775) for delegations), and we validated those signatures during permission traversal, we would gain a few benefits:

- Capabilities would be much harder to spoof, even with disk access (as MetaMask never stores private keys to disk)
- The wording of a permission would be bound with the consent given, and so analysis of why a person granted permission could always include analysis of the exact terms they consented to.

**Comment by rekmarks** [comment]
In the [new implementation](https://github.com/MetaMask/snaps-skunkworks/tree/54803e63e15732ffb561143c4197ba1de7cd019f/packages/controllers/src/permissions) of `rpc-cap`, permissions no longer contain any descriptions, as that responsibility is delegated to the host (which can then internationalize the descriptions as appropriate). Although there are still many enhancements to make, this particular issue no longer applies.
