### ISSUE TITLE
Support custom responses for rejection errors (like eth_accounts)

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/json-rpc-capabilities-middleware#23]
To not break current `eth_accounts` behavior, we _should_ return an empty array when the site is unauthorized. That's too bad, because we've established a very consistent pattern here, but for the sake of backwards compatibility, we probably need to do this.

It doesn't need to be within this module, maybe it's best handled outside of it, I'm not sure. Can the `next()` callback intercept an error with a custom response in `RpcEngine`? [I'm unclear](https://github.com/MetaMask/json-rpc-engine/blob/master/src/index.js#L81).

**Comment by rekmarks** [comment]
We should, can, and in some places already do, handle this behavior higher up in our stack. The empty array response behavior is preserved on `LoginPerSite` in places where it needs to be. We can easily break or keep the behavior for what the inpage provider returns.
