### ISSUE TITLE
Get working with .enable() method

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/json-rpc-capabilities-middleware#29]
This is out of the scope of this module, but this is a good place for putting it because this is where the Login per site project has mostly been managed.

Basically on the `metamask-inpage-provider`, we need to make an alias for this branch where `enable()` is polyfilled around this, ie with empty params it is translated to `{ method: 'requestPermissions': params: [{ eth_accounts: {} }]}`, and returns the result of a subsequent `eth_accounts` call.

We should expand the definition of `enable()` to accept some `enableOptions`, including `requestedPermissions` as an included object, which could trigger a permissions request also.

**Comment by rekmarks** [comment]
`ethereum.enable()` now calls the permissions controller in https://github.com/MetaMask/metamask-extension/tree/LoginPerSite, however #30 has yet to be resolved.

The functionality (selectedAddress, site metadata collection) managed by the provider approval controller needs to be transferred to the permissions controller.

`rpc-cap` should not require any further changes to accomplish any of these goals.

We need to decide whether folding the provider approval controller into the permissions controller is a requirement for this issue before it can be closed.

**Comment by rekmarks** [comment]
ProviderApproval controller folded into permissions controller, `ethereum.enable()` fully functional. Site metadata passing is also working, although keeping #30 open as we may change its implementation.
