### ISSUE TITLE
Fix inpage metadata passing

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/json-rpc-capabilities-middleware#30]
Need to include site metadata with each request after all. It's currently broken, and so site images/titles are not currently rendered correctly.

**Comment by rekmarks** [comment]
Update: currently working per the ProviderApproval pattern, but attempting to re-implement this by means of a transform stream at the point of request creation.

**Comment by rekmarks** [comment]
Implemented in the inpage provider using streams, see #34.
