### ISSUE TITLE
Ensure custom errors make it out of the middleware stack

### ISSUE THREAD

**Issue by rekmarks** [MetaMask/json-rpc-capabilities-middleware#36]
We want errors in `rpc-cap` of the form `end(error)` or `end(res.error)` to be forwarded to the background page and appear in the background console from `log.error(...)` calls therein.

We define custom errors in `rpc-cap`, but they're being swallowed by `json-rpc-engine` [here](https://github.com/MetaMask/json-rpc-capabilities-middleware/blob/master/index.ts#L166-L169), by [this function](https://github.com/MetaMask/json-rpc-engine/blob/master/src/index.js#L139-L144).

It was pointed out that this function in `json-rpc-engine` does not appear to be [compatible with the JSON-RPC standard](https://www.jsonrpc.org/specification#error_object). We should probably change its error handling to fix this.

2019-08-21: Pending https://github.com/MetaMask/metamask-extension/pull/7037 before fully complete.

**Comment by danfinlay** [comment]
Agreed rpc engine needs a breaking change here for the sake of good errors, which are critical to good developer experience and in turn good software on the platform.

**Comment by rekmarks** [comment]
Fixed after incorporating: https://github.com/MetaMask/metamask-extension/pull/7037
