### ISSUE TITLE
Add support for augmenting/updating caveats?

### ISSUE THREAD

**Issue by rekmarks** [MetaMask/json-rpc-capabilities-middleware#40]
If we do this, we'd add the ability to e.g. if `Domain A` has `eth_accounts` for `Account 1`, do not overwrite `[Domain A -> Account 1]` if `[Domain A -> Account 2]` is requested, but instead add Account 2 to the filterResponse caveat such that `[Domain A -> [Account 1, Account 2]]`

**Comment by danfinlay** [comment]
This is the kind of thing that makes me want to return function identifiers in response to permissions requests instead of basically updating a global ACL, because it is easier to define one attenuated method at a time than to write some permissions combining logic system.

**Comment by rekmarks** [comment]
Explicit updating of caveats was added via the addition of named caveats.
