### ISSUE TITLE
Security: Ensure requested `parentCapability` is overwritten

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/json-rpc-capabilities-middleware#45]
The permissions requestor submits an object of requested permissions objects, not an array.

We need to ensure that the object keys match the requested permissions' `parentCapability` fields, which we use to identify approved methods.

**Comment by rekmarks** [comment]
Fixed by checking that `Array.isArray(req.params)`.

**Comment by danfinlay** [comment]
Sorry, I was talking about each `IPermissionsRequest`'s `parentCapability` key needing to match its key in the `IRequestedPermissions` object, around [here](https://github.com/MetaMask/json-rpc-capabilities-middleware/commit/b417ed9fa5fd3ddadb6a85167db86899bac145bd#diff-ed009b6b86b017532ef0489c77de5100L508)

**Comment by rekmarks** [comment]
This attack vector was already closed by the actions of the following snippets: [here](https://github.com/MetaMask/json-rpc-capabilities-middleware/blob/master/index.ts#L365-L368) and [here](https://github.com/MetaMask/json-rpc-capabilities-middleware/blob/master/index.ts#L59-L69).

Essentially, even if there is a `parentCapability` property on one of the `Partial<IOcapLdCapability>` objects in the `IRequestedPermissions` object of a permissions request, we don't do anything with it.

In case we ever want to do something with the `parentCapability` property of `Partial<IOcapLdCapability>` objects of `IRequestedPermissions`, we should probably still prevent the key and `parentCapability` mismatch at the validation stage of `requestPermissionsMiddleware`. Currently, we only do anything with the `caveats` property.

**Comment by danfinlay** [comment]
Great, thanks for verifying 😅

**Comment by rekmarks** [comment]
Per above, added this as a safeguard and for modularization: https://github.com/MetaMask/json-rpc-capabilities-middleware/blob/master/index.ts#L483-L507
