### ISSUE TITLE
Document or remove namespaced methods.

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/json-rpc-capabilities-middleware#52]
Currently the `_` character is a special character that separates namespaces. This means two restricted methods `foo` and `foo_bar` would both be approved by a permission for `foo`.

This means either:
- We need to document this very well, and assume no one will ever accidentally create incorrectly underscored method names
- We should find a different way of permitting permitted method namespaces (which was intended to enable plugins, but could probably all be tucked behind a different subprovider).

**Comment by rekmarks** [comment]
This is no longer relevant as this package is being deprecated. Also, we're definitely keeping namespacing!
