### ISSUE TITLE
Ensure filterParams is requiring params to include its children

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/json-rpc-capabilities-middleware#53]
Add more tests of this variety:
https://github.com/MetaMask/json-rpc-capabilities-middleware/blob/master/test/caveats.js#L62

It may help to define the caveat with `isSuperset(b, a)` instead of `isSubset(a, b)`. Need to determine whether this is a readability improvement or a functional change.

**Comment by rekmarks** [comment]
This was solved by renaming `filterParams` to `requireParams` and adding some tests.
