### ISSUE TITLE
Re-requesting a granted permission should resemble user approval.

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/json-rpc-capabilities-middleware#6]
Currently re-triggers user confirmation, making for potentially obnoxious and redundant interactions.

**Comment by rekmarks** [comment]
Basically, we just want requests for already-granted permissions to die silently (but for, perhaps, some logging)?

**Comment by danfinlay** [comment]
That’s right.

**Comment by danfinlay** [comment]
Correction: We probably want them to _succeed_ silently. The experience for the dapp should be equivalent to repeated approval, since the user already expressed consent.

**Comment by danfinlay** [comment]
Bumping priority back a phase, b/c it's a nicety, not a hard requirement. We want to share the MVP as a proposed interface asap.

**Comment by rekmarks** [comment]
This is potentially thorny, and requires great care. It is made thorny by the existence of caveats, and specifically that their complexity/characteristics are something of an unknown quantity. Depending on what we choose to do, we need to make some potentially binding decisions about caveats.

The way I see, it we have two options:
1. Maintain existing behavior, and assume that if a permission is requested, it is requested for good reason. We encourage dapps to be sparing with their permissions requests, and establish that method calls, be they `eth_accounts` or something else, should be attempted before any permissions are requested.
2. If we receive a request for already-possessed permissions, we don't re-prompt. This requires establishing equivalency for permissions **and** caveats. I have an incomplete attempt to do so [here](https://github.com/MetaMask/json-rpc-capabilities-middleware/blob/hasPermissions/index.ts#L281-L340), with related caveat functions [here](https://github.com/MetaMask/json-rpc-capabilities-middleware/blob/hasPermissions/src/caveats.ts#L67-L118).

Some wrinkles with **2**:
  - So long as we only allow one of each permission type per domain, permission equivalency is as easy as a key lookup or, at worst, `permissionsArray.includes(permission)`. 
  - I attempt to establish caveat equivalency by caveat `type` and `value`, and ensure that the `value` - if it's an array - is sorted. To do this right, we would have to establish what can go into a caveat value, and ensure that permissions/caveats are only added through an interface we define.
    - If we allow permissions/caveats to be added willy-nilly, we can't compare them.

**Comment by danfinlay** [comment]
This is a good reason to stick with 1 for now, the same way we removed explicit delegation for now.

**Comment by rekmarks** [comment]
Postponing this. Eventually I think we should go for option **2**.

**Comment by rekmarks** [comment]
This is the wrong place for this issue, and this package is being deprecated.
