### ISSUE TITLE
Key permissions by method name rather than storing them in an array

### ISSUE THREAD

**Issue by rekmarks** [MetaMask/json-rpc-capabilities-middleware#68]
Permissions are currently stored as arrays under the key `permissions` in `domain` objects. Whenever we want to identify a specific permission, we have to iterate over this array. Permissions will always be unique by `parentCapability`, and we should simply key their storage thereby for more ergonomic permission retrieval.

_Note:_ `domain` is ocap lingo and equivalent to `origin` as used in the context of permissions in the extension.

Current structure:
```js
{
  [domain1]: {
    permissions: Array<IOcapLdCapability>,
    // ...
  },
  [domain2]: {
    permissions: Array<IOcapLdCapability>,
    // ...
  },
  // ...
}
```

Proposed structure:
```js
{
  [domain1]: {
    permissions: {
      [permission1]: IOcapLdCapability,
      [permission2]: IOcapLdCapability,
      // ...
    },
    // ...
  },
  [domain2]: {
    permissions: {
      [permission1]: IOcapLdCapability,
      [permission2]: IOcapLdCapability,
      // ...
    },
    // ...
  },
  // ...
}
```

**Comment by danfinlay** [comment]
I'm basically fine with this. The reason we used arrays was when we were baking delegations into the permissions table, and so you could have multiple permissions for a single method from multiple delegators, but we took that out, so it's now just a side effect of an un-pursued feature.

**Comment by rekmarks** [comment]
Closed by https://github.com/MetaMask/snaps-skunkworks/pull/132
