### ISSUE TITLE
support changing @context

### ISSUE THREAD

**Issue by shanejonas** [MetaMask/json-rpc-capabilities-middleware#92]
**Is your feature request related to a problem? Please describe.**
`@context` is hardcoded to `['https://github.com/MetaMask/rpc-cap']`

**Describe the solution you'd like**
Some way to customize the `@context` that is used

**Additional information**
https://github.com/MetaMask/rpc-cap/blob/940493ac65db3fea63e52cb04177ae1bd5244cf5/index.ts#L59

**Comment by rekmarks** [comment]
This repository is effectively deprecated in favor of the new `PermissionController`, currently hosted [here](https://github.com/MetaMask/snaps-skunkworks/tree/54803e63e15732ffb561143c4197ba1de7cd019f/packages/controllers/src/permissions). In that implementation, we have removed the `@context` field, and will only reintroduce it when we have a use case for it. We can assume that this issue will no longer apply when that time comes, and we can therefore close it.
